version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew clean build
  install:
    runtime-versions:
      java: openjdk8
      android: 28

artifacts:
  files:
     - './app/build/outputs/apk/*.apk'
     - './prebuilt/app-debug-androidTest.apk'
  discard-paths: yes
